### ISSUE TITLE
Undefined symbols for architecture i386: "_opendir$INODE64", referenced from:  _c_opendir in libfpm.a(src_filesystem_utilities.c.o)

### ISSUE THREAD

**Issue by barracuda156** [fortran-lang/fpm#829]
### Description

Linking of `fpm` fails on 10.6.8 `i386`: 
```
Undefined symbols for architecture i386:
  "_opendir$INODE64", referenced from:
      _c_opendir in libfpm.a(src_filesystem_utilities.c.o)
ld: symbol(s) not found for architecture i386
collect2: error: ld returned 1 exit status
```
Build log: https://build.macports.org/builders/ports-10.6_i386-builder/builds/104746/steps/install-port/logs/stdio

### Expected Behaviour

It should build successfully. Both `x86_64` and `ppc32` build fine on 10.6.8.

### Version of fpm

0.7.0

### Platform and Architecture

macOS 10.6.8/i386

### Additional Information

Compiler used: Clang-11

**Comment by krystophny** [comment]
@barracuda156 does this issue persist, and if yes, do you have current build logs (the old are not avanymore) and some details how one could reproduce this? In any case, i386 is not supported by Apple anymore for quite some time, so in case of doubt, I suggest to close this issue.

**Comment by barracuda156** [comment]
@krystophny I don’t know, but I will try to reproduce with the current release of `fpm` in a few days.
