### PR TITLE
fix: resolve MPI linker group issues and propagate library search paths

### LINKED ISSUE #1226: Difficulty building FTorch examples with fpm
### Description

I am in the process of setting up an fpm build approach for [FTorch](https://github.com/Cambridge-ICCS/FTorch), a Fortran interface for PyTorch. (More precisely, for the C++ backend libtorch.) See [`fpm.toml`](https://github.com/Cambridge-ICCS/FTorch/blob/77_fpm/fpm.toml) for my current attempt. I got some help from @everythingfunctional on this in an fpm workshop in September last year but didn't have time to work on getting it merged.

FTorch interfaces with libtorch via `iso_c_binding` so I provide `include-dir`, `external-modules`, and `link` entries. If I set `auto-examples = false` then running
```
fpm build \
  --profile debug \
  --compiler gfortran \
  --c-compiler gcc \
  --cxx-compiler g++ \
  --cxx-flag "-cpp -std=c++17 -I${Torch_DIR}/include -I${Torch_DIR}/include/torch/csrc/api/include -L${Torch_DIR}/lib" \
  --verbose
```
passes without error.

However, if I set `auto-examples = true` to build the examples then my local build (under gfortran 13.3.0) gives the link error
```
...
[ 62%]            tensor_manipulation
 + mkdir -p build/gfortran_91B283D9EEFAB29A/example/
 + gfortran   -cpp -Wall -Wextra -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -I/usr/lib/x86_64-linux-gnu/openmpi/lib/../../fortran/gfortran-mod-15/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/lib -fimplicit-none -Werror=implicit-interface -I././src  -Wl,--start-group  -L/usr/lib/x86_64-linux-gnu/openmpi/lib/fortran/gfortran -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lopen-rte -lopen-pal -lhwloc -levent_core -levent_pthreads -lm -lz build/gfortran_CF0CB3DAD3C4B334/FTorch/example_1_Tensor_tensor_manipulation.f90.o build/gfortran_A6431DBB512BBAC3/FTorch/libFTorch.a -ltorch -ltorch_cpu -lc10 -lstdc++ -o build/gfortran_91B283D9EEFAB29A/example/tensor_manipulation
/usr/bin/ld: missing --end-group; added as last command line option
/usr/bin/ld: cannot find -ltorch: No such file or directory
/usr/bin/ld: cannot find -ltorch_cpu: No such file or directory
/usr/bin/ld: cannot find -lc10: No such file or directory
collect2: error: ld returned 1 exit status
[ 66%]            tensor_manipulation  done.

/usr/bin/ld: missing --end-group; added as last command line option
/usr/bin/ld: cannot find -ltorch: No such file or directory
/usr/bin/ld: cannot find -ltorch_cpu: No such file or directory
/usr/bin/ld: cannot find -lc10: No such file or directory
collect2: error: ld returned 1 exit status
<ERROR> Compilation failed for object " tensor_manipulation "
<ERROR> stopping due to failed compilation
STOP 1
```
where here `tensor_manipulation` is the first example.

### Expected Behaviour

I expected that the examples build would pick up the link flags from the main FTorch build but it appears not. How do I get these to be picked up correctly?

### Version of fpm

0.10.0, alpha

### Platform and Architecture

Dell Latitude laptop, Ubuntu 24.04

### Additional Information

See https://github.com/Cambridge-ICCS/FTorch/pull/429.

### PR DESCRIPTION
**Pull request by ijatinydv**
This PR resolves the linking failures reported in #1226, specifically for projects using external C++ dependencies like libtorch.

**Key Fixes:**
- **MPI Grouping**: Added the missing `-Wl,--end-group` in `src/metapackage/fpm_meta_mpi.f90`. Previously, the unclosed group caused the linker to incorrectly wrap subsequent libraries into the circular dependency search, leading to resolution errors.
- **Flag Propagation**: Added logic in `src/fpm_targets.f90`to extract `-L` search paths from `c-flags` and `cxx-flags`. This ensures these paths are actually passed to the Fortran linker during the executable link step, which was previously missing.

**Testing:**
- Added and verified a new internal helper `extract_library_paths` with various inputs (single/multiple paths, no paths, and trailing flags).
- Ran `fpm test` and verified standard builds to ensure no regressions in core dependency handling.

Closes #1226

### CODE REVIEW

**Review by joewallwork — COMMENTED** [review]
Hi @ijatinydv, thanks very much for looking into this!

I tried building my draft FTorch branch mentioned in #1226 locally and this allowed me to get further. However, I get the following linking error when compiling the examples:
```
/usr/bin/ld: build/gfortran_86AF5D313414D558/tensor_manipulation/libtensor_manipulation.a(build_dependencies_FTorch_src_ctorch.cpp.o): in function `torch_jit_load':
ctorch.cpp:(.text+0x57e5): undefined reference to `torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::optional<c10::Device>, bool)'
/usr/bin/ld: build/gfortran_86AF5D313414D558/tensor_manipulation/libtensor_manipulation.a(build_dependencies_FTorch_src_ctorch.cpp.o): in function `c10::intrusive_ptr_target::~intrusive_ptr_target
()':                                             
ctorch.cpp:(.text._ZN3c1020intrusive_ptr_targetD2Ev[_ZN3c1020intrusive_ptr_targetD5Ev]+0x23e): undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, 
char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
...
```
Is this something that can be addressed in this PR or is it a configuration error on my side?

(Edited)

**Comment by joewallwork** [comment]
I think I did have a configuration issue above. On a new system I'm able to successfully build FTorch and then one of its examples with your fpm branch using the command
```
fpm build \
  --profile debug \
  --compiler "${FC}" \
  --c-compiler "${CC}" \
  --cxx-compiler "${CXX}" \
  --flag "-std=${FORTRAN_STANDARD}" \
  --cxx-flag "-I${Torch_DIR}/include -I${Torch_DIR}/include/torch/csrc/api/include" \
  --link-flag "-L${Torch_DIR}/lib" \
  --verbose
```
where `${Torch_DIR}` is the main Torch directory. However, I get `error while loading shared libraries: libtorch_cpu.so: cannot open shared object file: No such file or directory` errors when running the example, despite that shared library being in `${Torch_DIR}/lib`.

**Comment by joewallwork** [comment]
I can now confirm that I managed to figure out how to get this working in https://github.com/Cambridge-ICCS/FTorch/pull/599! It would be great if this PR could be merged so that we can pip install fpm in our workflow rather than building this branch.

Although the solution was to put `${Torch_DIR}/lib` in the `LD_LIBRARY_PATH`, which suggest that the `--link-flag` option still isn't being handled as expected.
